CIRDLES/Squid

.gitignore
common.gradle
squidApp/Schema/SHRIMP_PRAWN.xsd
squidApp/src/main/java/org/cirdles/squid/gui/SquidUIController.java
squidCore/src/main/java/org/cirdles/squid/constants/Squid3Constants.java
squidCore/src/main/java/org/cirdles/squid/core/PrawnFileHandler.java
squidCore/src/main/java/org/cirdles/squid/utilities/fileUtilities/CalamariFileUtilities.java
squidCore/src/main/resources/org/cirdles/squid/schema/SHRIMP_PRAWN.xsd

Moves PrawnFile schema to local folder to support lack of internet connectivity.

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/ExpressionManagerController.java
squidApp/src/main/java/org/cirdles/squid/gui/SpotManagerController.java
squidApp/src/main/java/org/cirdles/squid/gui/SquidUIController.java
squidApp/src/main/java/org/cirdles/squid/gui/TaskManagerController.java
squidApp/src/main/java/org/cirdles/squid/gui/dataReduction/ReductionManagerController.java
squidApp/src/main/resources/org/cirdles/squid/gui/SquidUIController.fxml
squidCore/src/main/java/org/cirdles/squid/constants/Squid3Constants.java
squidCore/src/main/java/org/cirdles/squid/core/CalamariReportsEngine.java
squidCore/src/main/java/org/cirdles/squid/core/PrawnFileHandler.java
squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java
squidCore/src/main/java/org/cirdles/squid/tasks/Task.java
squidCore/src/main/java/org/cirdles/squid/tasks/TaskInterface.java

Updates menu architecture and adds state of ReportsEngine.

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/ExpressionManagerController.java
squidApp/src/main/java/org/cirdles/squid/gui/RunsViewModel.java
squidApp/src/main/java/org/cirdles/squid/gui/SpotManagerController.java
squidApp/src/main/java/org/cirdles/squid/gui/SquidUI.java

Fixes https://github.com/CIRDLES/Squid/issues/34 and fixes https://github.com/CIRDLES/Squid/issues/35

Fixes #34 and fixes #35.

---

squidApp/src/main/java/org/cirdles/squid/gui/dataReduction/reducedDataReportManagerController.java

Forces report scenes to use Courier New

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/SpotManagerController.java
squidApp/src/main/resources/org/cirdles/squid/gui/SpotManager.fxml
squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java

Fixes issue #39 - duplicate names bug related to switch to case-insensitive spot names.

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/SquidUIController.java
squidCore/src/main/java/org/cirdles/squid/core/CalamariReportsEngine.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/functions/Concordia.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/functions/ConcordiaTW.java
squidCore/src/main/java/org/cirdles/squid/utilities/fileUtilities/CalamariFileUtilities.java

fixes https://github.com/CIRDLES/Squid/issues/46 and new version

Fixes #46 and new version.

---

common.gradle
squidCore/src/main/antlr/org/cirdles/squid/ExpressionsForSquid2.g4

Allows white space between function name and first paren

---

squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java
squidCore/src/main/java/org/cirdles/squid/shrimp/ShrimpFractionExpressionInterface.java
squidCore/src/main/java/org/cirdles/squid/tasks/Task.java

1. Completes removal of existing task artifacts when importing new task.
2. Provides for customizing various built-in expressions in response to isotope choice in task manager.

Task improvements.

---

squidCore/src/main/java/org/cirdles/squid/tasks/expressions/functions/Function.java

@mgaonach need to hide the logic operator "sqIf" in builder.

fixes issue with if and sqIf

---

squidApp/src/main/java/org/cirdles/squid/gui/expressions/ExpressionBuilderController.java
squidApp/src/main/resources/org/cirdles/squid/gui/RatiosManager.fxml
squidApp/src/main/resources/org/cirdles/squid/gui/expressions/ExpressionBuilder.fxml
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/spots/SpotSummaryDetails.java

- For summary expression: adds a their tab in peek to show rejected spots and change them when enabled.
- adds denominator and numerator to the ratio selection grid - #108

Rejected spot selection

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/MassesAuditController.java
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/MassStationAuditViewForShrimp.java
squidApp/src/main/java/org/cirdles/squid/gui/plots/PlotsController.java
squidApp/src/main/java/org/cirdles/squid/gui/plots/squid/WeightedMeanPlot.java
squidApp/src/main/resources/org/cirdles/squid/gui/plots/Plots.fxml
squidCore/src/main/java/org/cirdles/squid/reports/reportSpecifications/ReportSpecificationsUPbReferenceMaterials15Dig.java
squidCore/src/main/java/org/cirdles/squid/tasks/Task.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/functions/RobReg.java

Bug fixes and refactoring.

---

squidApp/src/main/java/org/cirdles/squid/gui/MassesAuditController.java
squidApp/src/main/java/org/cirdles/squid/gui/plots/squid/WeightedMeanPlot.java
squidApp/src/main/resources/org/cirdles/squid/gui/TaskManager.fxml
squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java
squidCore/src/main/java/org/cirdles/squid/tasks/TaskInterface.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/builtinExpressions/BuiltInExpressionsFactory.java

Fixes #152 and adds expression per @sbodorkos for perm3 math.

Misc. bug fixes.

---

squidApp/src/main/java/org/cirdles/squid/gui/expressions/ExpressionBuilderController.java

Fixes peek issue for TotalCps

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/TaskDesignerController.java
squidApp/src/main/java/org/cirdles/squid/gui/TaskManagerController.java
squidApp/src/main/java/org/cirdles/squid/gui/expressions/ExpressionBuilderController.java
squidApp/src/main/resources/org/cirdles/squid/gui/expressions/ExpressionBuilder.fxml
squidCore/src/main/java/org/cirdles/squid/tasks/Task.java
squidCore/src/main/java/org/cirdles/squid/tasks/TaskInterface.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/Expression.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/builtinExpressions/BuiltInExpressionsFactory.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/parsing/ExpressionParser.java

Fixes #281 .
New button at top of Expressions Manager shows an expression's dependency graphs for both calling and called expressions.

Fixes #281 and introduces expression dependency graphs.

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/SquidUIController.java
squidCore/src/main/java/org/cirdles/squid/dialogs/SquidMessageDialog.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/Expression.java
squidCore/src/main/java/org/cirdles/squid/tasks/squidTask25/TaskSquid25.java

fixes #306 - task import bug
addresses #307 - displays path to saved report file pending use-case exploration
addresses #308 - unhides aliased expressions for now
addresses #302 - provides warning when no reference material chosen

Bug fix and tweaks

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/SessionAuditController.java
squidApp/src/main/java/org/cirdles/squid/gui/TaskDesignerController.java
squidApp/src/main/java/org/cirdles/squid/gui/TaskManagerController.java
squidApp/src/main/resources/org/cirdles/squid/gui/SessionAudit.fxml
squidApp/src/main/resources/org/cirdles/squid/gui/TaskDesigner.fxml
squidApp/src/main/resources/org/cirdles/squid/gui/TaskManager.fxml
squidCore/src/main/java/org/cirdles/squid/constants/Squid3Constants.java
squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java
squidCore/src/main/java/org/cirdles/squid/tasks/taskDesign/TaskDesign.java

Fixes #329 Gui issues

---

squidApp/build.gradle
squidApp/src/main/java/org/cirdles/squid/gui/plots/PlotDisplayInterface.java
squidApp/src/main/java/org/cirdles/squid/gui/plots/PlotsController.java
squidApp/src/main/java/org/cirdles/squid/gui/plots/squid/WeightedMeanPlot.java
squidApp/src/main/java/org/cirdles/squid/gui/plots/topsoil/AbstractTopsoilPlot.java
squidApp/src/main/java/org/cirdles/squid/gui/plots/topsoil/TopsoilPlotTeraWasserburg.java
squidApp/src/main/java/org/cirdles/squid/gui/plots/topsoil/TopsoilPlotWetherill.java
squidApp/src/main/java/org/cirdles/squid/gui/topsoil/TopsoilDataFactory.java

Changes the Topsoil version to the most recent release ([v3.0.0-alpha4.3](https://github.com/CIRDLES/Topsoil/releases/tag/v3.0.0-alpha4.3)). Incorporates API changes accordingly.

Changes Topsoil dependency to most recent version

---

squidApp/build.gradle
squidApp/src/main/java/org/cirdles/squid/gui/topsoil/TopsoilDataFactory.java

Switches back to graying out ellipses upon deselection.

Updates Topsoil version

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/AbstractDataView.java
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/MassStationAuditViewForShrimp.java
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/TicGeneratorForAxes.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/PlotsController.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/squid/WeightedMeanPlot.java

fixes #372 and #373  by providing a more robust selector that includes crosshairs; also fixed sorting bug reported.

fixes #372 and #373 

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/commonLeadAssignment/CommonLeadAssignmentController.java
squidCore/build.gradle
squidCore/src/main/java/org/cirdles/squid/shrimp/ShrimpFraction.java
squidCore/src/main/java/org/cirdles/squid/tasks/Task.java

Fixes #392  and updates LudwigLibrary version to support weightedAvg of only two points.

Fixes bugs

---

squidApp/src/main/java/org/cirdles/squid/gui/MassesAuditController.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/squid/WeightedMeanPlot.java

Fixes bug in audit

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/expressions/ExpressionBuilderController.java
squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java
squidCore/src/main/java/org/cirdles/squid/tasks/TaskInterface.java

Addressed issue #462 - allowing for NU-switched custom expressions.

---

common.gradle
squidApp/build.gradle
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/plotControllers/AnyTwoExpressionsControlNode.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/plotControllers/ConcordiaControlNode.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/plotControllers/PlotsController.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/plotControllers/RefMatWeightedMeanControlNode.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/plotControllers/SamplesWeightedMeanToolBoxNode.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/plotControllers/ToolBoxNodeInterface.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/squid/PlotRefreshInterface.java
squidApp/src/main/java/org/cirdles/squid/gui/squidReportTable/SquidReportSettingsController.java
squidApp/src/main/resources/org/cirdles/squid/gui/SquidUIController.fxml
squidApp/src/main/resources/org/cirdles/squid/gui/squidReportTable/SquidReportSettings.fxml
squidCore/src/main/java/org/cirdles/squid/squidReports/squidReportColumns/SquidReportColumn.java
squidCore/src/main/java/org/cirdles/squid/tasks/Task.java
squidCore/src/main/java/org/cirdles/squid/utilities/csvSerialization/ReportSerializerToCSV.java
squidWeb/src/main/java/org/cirdles/squid/web/SquidReportingService.java

Updated to latest Topsoil and made UI refinements and bug fixes.

---

squidApp/src/main/java/org/cirdles/squid/gui/squidReportTable/SquidReportSettingsController.java
squidApp/src/main/resources/org/cirdles/squid/gui/squidReportTable/SquidReportSettings.fxml

added hints and instructions per @NicoleRayner 
also added multi-select feature for populating columns from expressions

Updated report manager LandF

---

squidApp/src/main/java/org/cirdles/squid/gui/SpotManagerController.java
squidApp/src/main/java/org/cirdles/squid/gui/SquidUIController.java
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/MassStationAuditViewForShrimp.java
squidApp/src/main/resources/org/cirdles/squid/gui/SquidUIController.fxml
squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java
squidCore/src/main/java/org/cirdles/squid/tasks/Task.java

Updated Splash screen and spot listing context menus

---

squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/squid/WeightedMeanPlot.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/topsoil/TopsoilDataFactory.java
squidApp/src/main/java/org/cirdles/squid/gui/expressions/ExpressionBuilderController.java
squidApp/src/main/resources/org/cirdles/squid/gui/SpotManager.fxml
squidCore/src/main/java/org/cirdles/squid/reports/reportSettings/ReportSettingsInterface.java
squidCore/src/main/java/org/cirdles/squid/utilities/xmlSerialization/XMLSerializerInterface.java
squidCore/src/main/resources/org/cirdles/squid/docs/contributorsContent.txt

Updated contributors list
Updated Xstream security
Refactored LandF
Updated peek to recognize functions and display values of all results from a Squid3 function
Fixed #603

Misc fixes

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/CountsAuditController.java
squidApp/src/main/java/org/cirdles/squid/gui/MassesAuditController.java
squidApp/src/main/java/org/cirdles/squid/gui/SquidUIController.java
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/AbstractDataView.java
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/SpeciesAMUAuditViewForShrimp.java
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/SpeciesCountsAuditViewForShrimp.java
squidApp/src/main/resources/org/cirdles/squid/gui/CountsAudit.fxml
squidApp/src/main/resources/org/cirdles/squid/gui/SquidUIController.fxml
squidCore/src/main/java/org/cirdles/squid/constants/Squid3Constants.java
squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java
squidCore/src/main/java/org/cirdles/squid/squidReports/squidWeightedMeanReports/SquidWeightedMeanReportEngine.java

Added feature requested in #596
Added feature requested in #599
Added feature requested in #605
refactoring and bug fixes

New features

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/MassesAuditController.java
squidApp/src/main/java/org/cirdles/squid/gui/SessionAuditController.java
squidApp/src/main/java/org/cirdles/squid/gui/SpotManagerController.java
squidApp/src/main/java/org/cirdles/squid/gui/SquidUI.java
squidApp/src/main/java/org/cirdles/squid/gui/SquidUIController.java
squidApp/src/main/java/org/cirdles/squid/gui/TaskManagerController.java
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/AbstractDataView.java
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/MassAuditRefreshInterface.java
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/SpeciesGraphs/SpeciesAMUAuditViewForShrimp.java
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/SpeciesGraphs/SpeciesCountsAuditViewForShrimp.java
squidApp/src/main/java/org/cirdles/squid/gui/dataViews/SpeciesGraphs/SpeciesGraphInterface.java
squidApp/src/main/resources/org/cirdles/squid/gui/SpotManager.fxml
squidApp/src/main/resources/org/cirdles/squid/gui/TaskEditor.fxml
squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java
squidCore/src/main/java/org/cirdles/squid/utilities/squidPrefixTree/SquidPrefixTree.java
squidCore/src/main/java/org/cirdles/squid/utilities/squidPrefixTree/SquidPrefixTreeNode.java
squidCore/src/main/java/org/cirdles/squid/utilities/stateUtilities/SquidLabData.java

refined naming interface
Completed naming upgrade
Fixed #626
Fixed #622
Fixed #621
Advanced functionality of mass audit screen zoom window.
Fixed #627

Various fixes.

---

squidApp/src/main/resources/org/cirdles/squid/gui/ProjectManager.fxml

This seems to work. I'm not so sure about how the change from 10.0.1 to 8.0.171 happened and whether it is significant or not.

Word wrap in project notes text box

---

squidAPI/src/main/java/org/cirdles/squid/Squid3API.java
squidAPI/src/main/java/org/cirdles/squid/Squid3Ink.java
squidApp/src/main/java/org/cirdles/squid/gui/parameters/ParametersManagerGUIController.java
squidApp/src/main/java/org/cirdles/squid/gui/utilities/fileUtilities/FileHandler.java
squidCore/src/main/java/org/cirdles/squid/projects/Squid3ProjectBasicAPI.java
squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/functions/Abs.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/functions/Exp.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/functions/Max.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/functions/Min.java
squidCore/src/main/java/org/cirdles/squid/utilities/stateUtilities/SquidLabData.java
squidCore/src/main/java/org/cirdles/squid/utilities/stateUtilities/SquidPersistentState.java

**added to Squid3Ink:**
public static SquidLabData getSquidLabData() 
public static SquidPersistentState getSquidPersistentState() 
**added to Squid3API:**
// project UI management
void setUseSBM(boolean doUse);
void setUseLinearRegression(boolean doUse);
void setPreferredIndexIsotope(Squid3Constants.IndexIsoptopesEnum isotope);
void setAutoExcludeSpots(boolean doAutoExclude);
void setMinimumExternalSigma206238(double minExternalSigma);
void setMinimumExternalSigma208232(double minExternalSigma);
void setDefaultCommonPbModel(ParametersModel commonPbModel);
void setDefaultPhysicalConstantsModel(ParametersModel physicalConstantsModel);
void setDefaultParametersFromCurrentChoices();
void refreshModelsAction();

Addressed #635

---

common.gradle
squidAPI/src/main/java/org/cirdles/squid/Squid3API.java
squidAPI/src/main/java/org/cirdles/squid/Squid3Ink.java
squidApp/src/main/java/org/cirdles/squid/gui/SpotManagerController.java
squidApp/src/main/java/org/cirdles/squid/gui/SquidUI.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/plotControllers/RefMatWeightedMeanToolBoxNode.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/plotControllers/SamplesWeightedMeanToolBoxNode.java
squidApp/src/main/java/org/cirdles/squid/gui/utilities/fileUtilities/FileHandler.java
squidCore/src/main/java/org/cirdles/squid/projects/Squid3ProjectBasicAPI.java
squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java
squidCore/src/main/java/org/cirdles/squid/tasks/Task.java

fixed #647 
fixed #643 
Added functionality to SquidInk API

Various issues and API update

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/squidReportTable/SquidReportSettingsController.java
squidApp/src/main/resources/org/cirdles/squid/gui/squidReportTable/SquidReportSettings.fxml
squidCore/src/main/java/org/cirdles/squid/shrimp/CommonLeadSpecsForSpot.java
squidCore/src/main/java/org/cirdles/squid/shrimp/ShrimpFraction.java
squidCore/src/main/java/org/cirdles/squid/shrimp/ShrimpFractionExpressionInterface.java
squidCore/src/main/java/org/cirdles/squid/tasks/Task.java
squidCore/src/main/java/org/cirdles/squid/tasks/TaskInterface.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/builtinExpressions/BuiltInExpressionsFactory.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/expressionTrees/ExpressionTree.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/functions/Rad8corConcRho.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/spots/SpotFieldNode.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/spots/SpotTaskMetaDataNode.java

Report metadata fields added for  Stacey Kramer and for Task.

Bug fixes and addressed issue #667

---

common.gradle
squidAPI/src/main/java/org/cirdles/squid/Squid3API.java
squidAPI/src/main/java/org/cirdles/squid/Squid3Ink.java
squidApp/build.gradle
squidApp/src/main/java/org/cirdles/squid/gui/ProjectManagerController.java
squidApp/src/main/java/org/cirdles/squid/gui/SquidUIController.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/plotControllers/RefMatCalibrationConstantWMToolBoxNode.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/plots/plotControllers/RefMatConcordiaToolBoxNode.java
squidCore/build.gradle
squidCore/src/main/java/org/cirdles/squid/projects/Squid3ProjectBasicAPI.java
squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java
squidCore/src/main/java/org/cirdles/squid/tasks/Task.java

Fixed #680 and #681

---

.travis.yml
common.gradle
customBuildForGradle73.sh
squidApp/src/main/java/org/cirdles/squid/gui/SquidUIController.java
squidApp/src/main/java/org/cirdles/squid/gui/parameters/ParametersManagerGUIController.java
squidApp/src/main/java/org/cirdles/squid/gui/squidReportTable/SquidReportSettingsController.java
squidApp/src/main/java/org/cirdles/squid/gui/utilities/fileUtilities/FileHandler.java
squidCore/src/main/java/org/cirdles/squid/tasks/Task.java
squidCore/src/main/java/org/cirdles/squid/utilities/stateUtilities/SquidLabData.java
squidCore/src/main/java/org/cirdles/squid/utilities/stateUtilities/SquidPersistentState.java

Updated persistentState properties

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/SquidUIController.java
squidApp/src/main/java/org/cirdles/squid/gui/TaskEditorController.java
squidApp/src/main/java/org/cirdles/squid/gui/utilities/fileUtilities/FileHandler.java

Issue #692 and #693

---

common.gradle
squidAPI/src/main/java/org/cirdles/squid/Squid3Ink.java
squidApp/src/main/java/org/cirdles/squid/gui/RatiosManagerController.java
squidApp/src/main/java/org/cirdles/squid/gui/TaskEditorController.java
squidApp/src/main/java/org/cirdles/squid/gui/squidReportTable/SquidReportSettingsController.java
squidCore/src/main/java/org/cirdles/squid/algorithms/weightedMeans/WeightedMeanCalculators.java
squidCore/src/main/java/org/cirdles/squid/parameters/parameterModels/referenceMaterialModels/ReferenceMaterialModel.java
squidCore/src/main/java/org/cirdles/squid/projects/SquidProject.java
squidCore/src/main/java/org/cirdles/squid/shrimp/ShrimpFraction.java
squidCore/src/main/java/org/cirdles/squid/squidReports/squidReportTables/SquidReportTable.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/Expression.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/expressionTrees/ExpressionTree.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/expressionTrees/ExpressionTreeInterface.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/functions/Function.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/parsing/ShuntingYard.java
squidCore/src/main/java/org/cirdles/squid/tasks/squidTask25/TaskSquid25.java
squidCore/src/main/java/org/cirdles/squid/utilities/fileUtilities/CalamariFileUtilities.java
squidCore/src/test/java/org/cirdles/squid/ElementComparer.java
squidCore/src/test/java/org/cirdles/squid/core/ExpressionXMLConverterTest.java

Bug fix and refactoring

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/SquidUIController.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/commonLeadAssignment/CommonLeadAssignmentController.java
squidApp/src/main/java/org/cirdles/squid/gui/dateInterpretations/countCorrections/CountCorrectionsController.java
squidCore/src/main/java/org/cirdles/squid/tasks/expressions/builtinExpressions/BuiltInExpressionsDataDictionary.java
squidCore/src/main/resources/org/cirdles/squid/schema/SHRIMP_PRAWN.xsd

Fixed #754 and refactored

---

common.gradle
squidApp/src/main/java/org/cirdles/squid/gui/SquidUIController.java
squidCore/src/main/java/org/cirdles/squid/core/CalamariReportsEngine.java
squidCore/src/main/java/org/cirdles/squid/tasks/Task.java
squidCore/src/main/java/org/cirdles/squid/tasks/TaskInterface.java
squidCore/src/main/java/org/cirdles/squid/utilities/fileUtilities/ZipUtility.java
squidCore/src/test/java/org/cirdles/squid/core/PrawnFileHandlerIT.java

to zip the per scan reports locally and then write zip to target folder.

Changed report engine 
